# Generated by Django 2.2.7 on 2019-11-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseHourse', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('studentDateOfBirth', models.DateField()),
                ('studentStatus', models.CharField(max_length=50)),
                ('studentGPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couesePractical', models.IntegerField(default=0)),
                ('courseYearWork', models.IntegerField(default=0)),
                ('finalExamAbsent', models.BooleanField()),
                ('finalExamScore', models.FloatField()),
                ('courseTotalScore', models.FloatField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GridDemoApp.Course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GridDemoApp.Student')),
            ],
        ),
    ]
