# Generated by Django 2.2.6 on 2019-10-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlineForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescore',
            name='score',
            field=models.IntegerField(default='0'),
        ),
    ]
