# Generated by Django 2.2.6 on 2019-10-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlineForm', '0002_auto_20191027_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescore',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='studentName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
